# Teste Pull Request
steps:
  - id: "Build image from Dockerfile.prod"
    name: "docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/app-lavarel:$SHORT_SHA",
        "-f",
        "Dockerfile.prod",
        ".",
      ]

  - id: "Pushing image"
    name: "docker"
    args: ["push", "gcr.io/$PROJECT_ID/app-lavarel:$SHORT_SHA"]

  - id: 'Ajusting deployment file - k8s'
    name: "gcloud"
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        sed 's#img-app-deployment#gcr.io/$PROJECT_ID/app-laravel:$SHORT_SHA#g' .k8s/app/deployment.yaml > k8s/app/deployment-new.yaml
        cat k8s/app/deployment-new.yaml
