apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis-service
    role: master
spec:
  selector:
    app: redis-master
  ports:
    - port: 6379
      targetPort: 6379
